spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/persons
    username: developer
    password: Developer@1234

  flyway:
    url: jdbc:mysql://localhost:3306/persons
    user: developer
    password: Developer@1234
